#This configuration file was written by: org.eclipse.oomph.p2.internal.core.AgentImpl
#Mon Sep 21 09:44:18 IST 2026
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.41.0.20260903-0719
eclipse.p2.data.area=file\:/C\:/Users/ramte/.p2/
eclipse.p2.profile=C__25 aug 2026 Java Backend_Wrokspace_eclipse
eclipse.product=org.eclipse.epp.package.java.product
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.5.700.v20251111-1031.jar@1\:start
osgi.bundles.defaultStartLevel=4
osgi.framework=file\:/C\:/Users/ramte/.p2/pool/plugins/org.eclipse.osgi_3.24.300.v20260721-1251.jar
osgi.framework.extensions=reference\:file\:org.eclipse.osgi.compatibility.state_1.3.0.v20251022-1724.jar
osgi.instance.area.default=@user.home/workspace
osgi.splashPath=file\:/C\:/Users/ramte/.p2/pool/plugins/org.eclipse.epp.package.common_4.41.0.20260903-0719
